Go to http://jalammar.github.io/illustrated-bert/ and read about bert pretraining, heads.

In [ ]:
import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

text = "a nice walk by the river bank"
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs, output_attentions=True)

attention_weights = outputs.attentions

In [ ]:
inputs

{'input_ids': tensor([[ 101, 1037, 3835, 3328, 2011, 1996, 2314, 2924,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
len(attention_weights) # BERT has 12 layers

12

In [ ]:
attention_weights[0].shape # number of attention heads is 12BERT's attention mechanism is fascinating.
1, 12, 9, 9

NameError: name 'attention_weights' is not defined

In [ ]:
layer = 0
attention_head=0
attention_weights[layer][0, attention_head, :, :]

tensor([[0.0608, 0.1598, 0.0426, 0.0411, 0.1300, 0.1476, 0.0439, 0.0756, 0.2986],
        [0.1360, 0.0947, 0.1049, 0.1290, 0.0972, 0.1380, 0.0952, 0.1052, 0.0999],
        [0.0745, 0.0492, 0.1031, 0.1193, 0.1089, 0.0523, 0.1666, 0.1197, 0.2063],
        [0.0673, 0.0643, 0.2049, 0.0621, 0.0452, 0.1225, 0.1720, 0.1157, 0.1460],
        [0.1437, 0.0783, 0.1092, 0.1129, 0.1310, 0.0872, 0.0829, 0.0645, 0.1901],
        [0.1133, 0.0939, 0.1178, 0.0825, 0.1463, 0.1467, 0.1050, 0.0830, 0.1115],
        [0.0601, 0.0187, 0.1901, 0.2568, 0.0323, 0.0157, 0.1152, 0.2320, 0.0790],
        [0.1535, 0.0165, 0.2493, 0.1617, 0.0480, 0.0132, 0.1857, 0.0879, 0.0841],
        [0.1089, 0.1646, 0.0673, 0.0485, 0.1568, 0.1502, 0.0684, 0.0496, 0.1857]],
       grad_fn=<SliceBackward0>)

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

# A Visual Notebook to Using BERT for the First TIme.ipynb



<img src="https://jalammar.github.io/images/distilBERT/bert-distilbert-sentence-classification.png" />

In this notebook, we will use pre-trained deep learning model to process some text. We will then use the output of that model to classify the text. The text is a list of sentences from film reviews. And we will calssify each sentence as either speaking "positively" about its subject of "negatively".

## Models: Sentence Sentiment Classification
Our goal is to create a model that takes a sentence (just like the ones in our dataset) and produces either 1 (indicating the sentence carries a positive sentiment) or a 0 (indicating the sentence carries a negative sentiment). We can think of it as looking like this:

<img src="https://jalammar.github.io/images/distilBERT/sentiment-classifier-1.png" />

Under the hood, the model is actually made up of two model.

* DistilBERT processes the sentence and passes along some information it extracted from it on to the next model. DistilBERT is a smaller version of BERT developed and open sourced by the team at HuggingFace. It’s a lighter and faster version of BERT that roughly matches its performance.
* The next model, a basic Logistic Regression model from scikit learn will take in the result of DistilBERT’s processing, and classify the sentence as either positive or negative (1 or 0, respectively).

The data we pass between the two models is a vector of size 768. We can think of this of vector as an embedding for the sentence that we can use for classification.


<img src="https://jalammar.github.io/images/distilBERT/distilbert-bert-sentiment-classifier.png" />

## Dataset
The dataset we will use in this example is [SST2](https://nlp.stanford.edu/sentiment/index.html), which contains sentences from movie reviews, each labeled as either positive (has the value 1) or negative (has the value 0):


<table class="features-table">
  <tr>
    <th class="mdc-text-light-green-600">
    sentence
    </th>
    <th class="mdc-text-purple-600">
    label
    </th>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      a stirring , funny and finally transporting re imagining of beauty and the beast and 1930s horror films
    </td>
    <td class="mdc-bg-purple-50">
      1
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      apparently reassembled from the cutting room floor of any given daytime soap
    </td>
    <td class="mdc-bg-purple-50">
      0
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      they presume their audience won't sit still for a sociology lesson
    </td>
    <td class="mdc-bg-purple-50">
      0
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      this is a visually stunning rumination on love , memory , history and the war between art and commerce
    </td>
    <td class="mdc-bg-purple-50">
      1
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      jonathan parker 's bartleby should have been the be all end all of the modern office anomie films
    </td>
    <td class="mdc-bg-purple-50">
      1
    </td>
  </tr>
</table>

## Installing the transformers library
Let's start by installing the huggingface transformers library so we can load our deep learning NLP model.

In [ ]:
!pip install transformers --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.29.2-py3-none-any.whl (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 59.6 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.0)
Collecting huggingface-hub<1.0,>=0.14.1 (from transformers)
  Downloading huggingface_hub-0.14.1-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 12.9 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.27.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers)
  Downloading tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 67.3 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.65.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (2023.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Installing collected packages: tokenizers, huggingface-hub, transformers
Successfully installed huggingface-hub-0.14.1 tokenizers-0.13.3 transformers-4.29.2

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
import warnings
warnings.filterwarnings('ignore')

## Importing the dataset
We'll use pandas to read the dataset and load it into a dataframe.

In [ ]:
df = pd.read_csv('https://github.com/clairett/pytorch-sentiment-classification/raw/master/data/SST2/train.tsv', delimiter='\t', header=None)

For performance reasons, we'll only use 2,000 sentences from the dataset

In [ ]:
batch_1 = df[:2000]

In [ ]:
df

                                                      0  1
0     a stirring , funny and finally transporting re...  1
1     apparently reassembled from the cutting room f...  0
2     they presume their audience wo n't sit still f...  0
3     this is a visually stunning rumination on love...  1
4     jonathan parker 's bartleby should have been t...  1
...                                                 ... ..
6915  painful , horrifying and oppressively tragic ,...  1
6916  take care is nicely performed by a quintet of ...  0
6917  the script covers huge , heavy topics in a bla...  0
6918  a seriously bad film with seriously warped log...  0
6919  a deliciously nonsensical comedy about a city ...  1

[6920 rows x 2 columns]

We can ask pandas how many sentences are labeled as "positive" (value 1) and how many are labeled "negative" (having the value 0)

In [ ]:
batch_1[1].value_counts()

1    1041
0     959
Name: 1, dtype: int64

## Loading the Pre-trained BERT model
Let's now load a pre-trained BERT model.

In [ ]:
# For DistilBERT:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer,
                                                    'distilbert-base-uncased')

## Want BERT instead of distilBERT? Uncomment the following line:
#model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_projector.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_layer_norm.weight', 'vocab_transform.bias', 'vocab_projector.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [ ]:
model

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(in_features=3072, out_features=768, bias=True)
          (activation): GELUActivation()
        )
        (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      )
    )
  )
)

Right now, the variable `model` holds a pretrained distilBERT model -- a version of BERT that is smaller, but much faster and requiring a lot less memory.

## Model #1: Preparing the Dataset
Before we can hand our sentences to BERT, we need to so some minimal processing to put them in the format it requires.

### Tokenization
Our first step is to tokenize the sentences -- break them up into word and subwords in the format BERT is comfortable with.

In [ ]:
tokenized = batch_1[0].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))

In [ ]:
tokenized[14], tokenizer.decode(tokenized[11])

([101,
  2089,
  2022,
  2062,
  8991,
  4818,
  2084,
  13749,
  18595,
  3560,
  1010,
  2021,
  2009,
  4152,
  1996,
  3105,
  2589,
  102],
 "[CLS] the most repugnant adaptation of a classic text since roland joff and demi moore's the scarlet letter [SEP]")

In [ ]:
tokenizer.encode(batch_1[0][10], add_special_tokens=True)

[101,
 1037,
 16376,
 19240,
 2005,
 3451,
 1998,
 3167,
 2969,
 5456,
 1998,
 1037,
 27263,
 17933,
 4226,
 3193,
 1997,
 1037,
 2210,
 4622,
 2088,
 102]

In [ ]:
batch_1[0][11]

"the most repugnant adaptation of a classic text since roland joff and demi moore 's the scarlet letter"

<img src="https://jalammar.github.io/images/distilBERT/bert-distilbert-tokenization-2-token-ids.png" />

### Padding
After tokenization, `tokenized` is a list of sentences -- each sentences is represented as a list of tokens. We want BERT to process our examples all at once (as one batch). It's just faster that way. For that reason, we need to pad all lists to the same size, so we can represent the input as one 2-d array, rather than a list of lists (of different lengths).

In [ ]:
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)
padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])

In [ ]:
padded[1]

array([  101,  4593,  2128, 27241, 23931,  2013,  1996,  6276,  2282,
        2723,  1997,  2151,  2445, 12217,  7815,   102,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0])

Our dataset is now in the `padded` variable, we can view its dimensions below:

In [ ]:
np.array(padded).shape

(2000, 59)

### Masking
If we directly send `padded` to BERT, that would slightly confuse it. We need to create another variable to tell it to ignore (mask) the padding we've added when it's processing its input. That's what attention_mask is:

In [ ]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape
attention_mask[2], padded[2]

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  101,  2027,  3653, 23545,  2037,  4378, 24185,  1050,  1005,
         1056,  4133,  2145,  2005,  1037, 11507, 10800,  1010,  2174,
        14036,  2135,  3591,  1010,  2061,  2027, 19817,  4140,  2041,
         1996,  7511,  2671,  4349,  3787,  1997, 11829,  7168,  9219,
         1998, 28971,  2308,  1999,  8301,  8737,  2100,  4253,   102,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]))

## Model #1: And Now, Deep Learning!
Now that we have our model and inputs ready, let's run our model!

<img src="https://jalammar.github.io/images/distilBERT/bert-distilbert-tutorial-sentence-embedding.png" />

The `model()` function runs our sentences through BERT. The results of the processing will be returned into `last_hidden_states`.

In [ ]:
input_ids = torch.tensor(padded)
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
   outputs = model(input_ids, attention_mask=attention_mask)
help(outputs)

Help on BaseModelOutput in module transformers.modeling_outputs object:

class BaseModelOutput(transformers.utils.generic.ModelOutput)
 |  BaseModelOutput(last_hidden_state: torch.FloatTensor = None, hidden_states: Optional[Tuple[torch.FloatTensor]] = None, attentions: Optional[Tuple[torch.FloatTensor]] = None) -> None
 |
 |  Base class for model's outputs, with potential hidden states and attentions.
 |
 |  Args:
 |      last_hidden_state (`torch.FloatTensor` of shape `(batch_size, sequence_length, hidden_size)`):
 |          Sequence of hidden-states at the output of the last layer of the model.
 |      hidden_states (`tuple(torch.FloatTensor)`, *optional*, returned when `output_hidden_states=True` is passed or when `config.output_hidden_states=True`):
 |          Tuple of `torch.FloatTensor` (one for the output of the embeddings, if the model has an embedding layer, +
 |          one for the output of each layer) of shape `(batch_size, sequence_length, hidden_size)`.
 |
 |          Hidden-states of the model at the output of each layer plus the optional initial embedding outputs.
 |      attentions (`tuple(torch.FloatTensor)`, *optional*, returned when `output_attentions=True` is passed or when `config.output_attentions=True`):
 |          Tuple of `torch.FloatTensor` (one for each layer) of shape `(batch_size, num_heads, sequence_length,
 |          sequence_length)`.
 |
 |          Attentions weights after the attention softmax, used to compute the weighted average in the self-attention
 |          heads.
 |
 |  Method resolution order:
 |      BaseModelOutput
 |      transformers.utils.generic.ModelOutput
 |      collections.OrderedDict
 |      builtins.dict
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __init__(self, last_hidden_state: torch.FloatTensor = None, hidden_states: Optional[Tuple[torch.FloatTensor]] = None, attentions: Optional[Tuple[torch.FloatTensor]] = None) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'attentions': typing.Optional[typing.Tuple[torch.Fl...
 |
 |  __dataclass_fields__ = {'attentions': Field(name='attentions',type=typ...
 |
 |  __dataclass_params__ = _DataclassParams(init=True,repr=True,eq=True,or...
 |
 |  __hash__ = None
 |
 |  __match_args__ = ('last_hidden_state', 'hidden_states', 'attentions')
 |
 |  attentions = None
 |
 |  hidden_states = None
 |
 |  last_hidden_state = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from transformers.utils.generic.ModelOutput:
 |
 |  __delitem__(self, *args, **kwargs)
 |      Delete self[key].
 |
 |  __getitem__(self, k)
 |      x.__getitem__(y) <==> x[y]
 |
 |  __post_init__(self)
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  __setitem__(self, key, value)
 |      Set self[key] to value.
 |
 |  pop(self, *args, **kwargs)
 |      od.pop(key[,default]) -> v, remove specified key and return the corresponding value.
 |
 |      If the key is not found, return the default if given; otherwise,
 |      raise a KeyError.
 |
 |  setdefault(self, *args, **kwargs)
 |      Insert key with a value of default if key is not in the dictionary.
 |
 |      Return the value for key if key is in the dictionary, else default.
 |
 |  to_tuple(self) -> Tuple[Any]
 |      Convert self to a tuple containing all the attributes/keys that are not `None`.
 |
 |  update(self, *args, **kwargs)
 |      D.update([E, ]**F) -> None.  Update D from dict/iterable E and F.
 |      If E is present and has a .keys() method, then does:  for k in E: D[k] = E[k]
 |      If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v
 |      In either case, this is followed by: for k in F:  D[k] = F[k]
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from collections.OrderedDict:
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __ior__(self, value, /)
 |      Return self|=value.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __reduce__(...)
 |      Return state information for pickling
 |
 |  __reversed__(...)
 |      od.__reversed__() <==> reversed(od)
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __sizeof__(...)
 |      D.__sizeof__() -> size of D in memory, in bytes
 |
 |  clear(...)
 |      od.clear() -> None.  Remove all items from od.
 |
 |  copy(...)
 |      od.copy() -> a shallow copy of od
 |
 |  items(...)
 |      D.items() -> a set-like object providing a view on D's items
 |
 |  keys(...)
 |      D.keys() -> a set-like object providing a view on D's keys
 |
 |  move_to_end(self, /, key, last=True)
 |      Move an existing element to the end (or beginning if last is false).
 |
 |      Raise KeyError if the element does not exist.
 |
 |  popitem(self, /, last=True)
 |      Remove and return a (key, value) pair from the dictionary.
 |
 |      Pairs are returned in LIFO order if last is true or FIFO order if false.
 |
 |  values(...)
 |      D.values() -> an object providing a view on D's values
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from collections.OrderedDict:
 |
 |  fromkeys(iterable, value=None) from builtins.type
 |      Create a new ordered dictionary with keys from iterable and values set to value.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from collections.OrderedDict:
 |
 |  __dict__
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from builtins.dict:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  get(self, key, default=None, /)
 |      Return the value for key if key is in the dictionary, else default.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from builtins.dict:
 |
 |  __class_getitem__(...) from builtins.type
 |      See PEP 585
 |
 |  ----------------------------------------------------------------------
 |  Static methods inherited from builtins.dict:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.

In [ ]:
outputs.last_hidden_state.numpy().shape
#outputs is called in the original notebook last_hidden_states
#last_hidden_state (torch.FloatTensor of shape (batch_size, sequence_length, hidden_size))
            # a Sequence of hidden-states at the output of the last layer of the model.

(2000, 59, 768)

Let's slice only the part of the output that we need. That is the output corresponding the first token of each sentence. The way BERT does sentence classification, is that it adds a token called `[CLS]` (for classification) at the beginning of every sentence. The output corresponding to that token can be thought of as an embedding for the entire sentence.

<img src="https://jalammar.github.io/images/distilBERT/bert-output-tensor-selection.png" />

We'll save those in the `features` variable, as they'll serve as the features to our logitics regression model.

In [ ]:
features = outputs.last_hidden_state[:,0,:].numpy()

In [ ]:
features[2]

array([-5.06335422e-02,  7.20394701e-02, -2.95973364e-02, -1.40354440e-01,
       -8.06072578e-02, -1.03232235e-01,  4.26805198e-01,  2.45677799e-01,
        4.69817929e-02, -1.48649126e-01, -1.25710443e-01, -1.91825465e-03,
        9.26228985e-03,  3.26775342e-01, -6.11782912e-03,  4.95377451e-01,
       -6.87092468e-02,  1.56111658e-01,  2.09620714e-01, -7.67024159e-02,
        2.29849786e-01, -2.94079781e-01, -6.16846234e-02,  1.86952829e-01,
        9.29776654e-02, -1.10866748e-01,  1.28718749e-01,  1.06657110e-01,
       -3.78832826e-03,  8.16244483e-02,  9.48646814e-02,  1.63880482e-01,
        1.62678175e-02, -3.22637439e-01,  1.60817672e-02, -9.81822014e-02,
        7.04560652e-02, -1.36364298e-02,  1.91389620e-01,  1.41441017e-01,
        1.14794791e-01,  1.06009059e-01,  2.02923253e-01,  5.09373546e-02,
       -5.49217649e-02, -3.81684840e-01, -2.59828091e+00, -1.97298735e-01,
       -4.09966022e-01, -2.61619031e-01,  2.55241632e-01,  1.81375220e-01,
        2.37444192e-01,  3.82537812e-01,  1.87904224e-01,  2.78487951e-01,
       -3.14222097e-01,  3.57836992e-01,  1.88748091e-01,  1.53274864e-01,
        1.94534421e-01,  3.48314315e-01, -1.03250980e-01,  1.39722992e-02,
       -3.39338928e-01,  2.70664960e-01, -1.08501263e-01,  1.71161324e-01,
       -2.20826626e-01,  4.86189216e-01, -3.61546129e-01, -1.74784154e-01,
        2.55697995e-01, -1.24530323e-01, -8.96621495e-02,  1.26473263e-01,
        3.05375636e-01,  1.78745180e-01, -3.36969435e-01,  8.61214250e-02,
       -3.00669037e-02,  5.15095294e-01,  3.67548585e-01,  3.01055163e-01,
        1.39986709e-01,  1.61449164e-01, -2.43204925e-02,  1.11326337e-01,
        1.75583601e-01,  3.84400755e-01, -3.93910944e-01, -1.03132591e-01,
       -1.04187235e-01,  1.69465512e-01,  4.27117556e-01, -3.09826821e-01,
        1.91207781e-01,  1.18545927e-02,  3.44266146e-01,  2.26201817e-01,
        3.19982916e-01, -4.76818494e-02,  3.08111031e-02, -4.96359318e-01,
       -4.70965579e-02, -1.15758643e-01,  2.92963590e-02, -5.96965551e-01,
       -2.49359384e-02, -2.03591180e+00,  1.97366968e-01,  1.13866076e-01,
        1.28482813e-02, -3.30158561e-01,  7.51555562e-02,  6.04313761e-02,
        1.89185888e-01, -8.53263214e-03, -1.74356773e-01,  1.92528769e-01,
        1.07440874e-02,  2.32215971e-01, -1.68551549e-01, -2.57389009e-01,
        4.42800224e-02,  1.79144349e-02,  9.83900204e-03,  2.81922724e-02,
        1.93830341e-01,  1.78210929e-01,  3.95000726e-01,  3.72270435e-01,
       -9.37529132e-02, -4.10514116e-01, -2.72920966e-01,  2.95984328e-01,
        5.77007353e-01,  8.36175382e-02, -2.16101110e-02,  1.41360864e-01,
       -4.83560681e-01,  6.58938719e-04, -2.58980918e+00,  2.81864554e-01,
        4.74138945e-01, -5.17294966e-02,  2.83021256e-02,  4.71679084e-02,
       -7.69416541e-02,  4.06637862e-02,  1.14600947e-02, -6.20373711e-02,
       -3.19687843e-01, -9.46873575e-02, -2.17311177e-02,  3.86473276e-02,
       -1.08578026e-01,  4.10550050e-02,  2.94119716e-01,  2.25471810e-01,
        3.51197660e-01, -1.05598524e-01, -4.14684922e-01, -2.50980556e-01,
        2.77101155e-02, -4.60637361e-03,  3.15409809e-01, -5.28387465e-02,
        8.35646316e-02,  1.63819045e-01,  2.75144964e-01,  8.90051294e-03,
        3.91670823e-01, -1.29680693e-01,  3.17464530e-01,  1.68886617e-01,
       -6.52889311e-02,  2.74344146e-01, -1.25185281e-01,  2.37583630e-02,
       -3.08777124e-01,  4.66445118e-01,  1.77014872e-01,  1.04438988e-02,
       -1.67826802e-01, -1.85092360e-01, -1.84251601e-03, -3.49463195e-01,
       -2.76601791e-01,  1.42582089e-01, -6.53012097e-02, -1.17124699e-01,
        6.07780814e-02, -2.56622434e-01,  3.12083840e-01, -1.62856141e-03,
        1.15621619e-01, -2.66693801e-01, -8.87515992e-02, -8.50878805e-02,
       -1.00579381e-01,  1.34297952e-01, -1.05464878e-02,  2.46947989e-01,
       -2.84360975e-01,  3.51951623e+00, -1.69091020e-02, -8.83648396e-02,
       -1.14267953e-02,  1.71456978e-01, -2.26526961e-01, -2.55816817e-01,
       -8.36402061e-04,  7.87012465e-03, -4.90309671e-02, -5.99395223e-02,
        3.95361811e-01, -1.30812034e-01, -1.05557643e-01, -1.19267948e-01,
        4.34587412e-02,  1.57090977e-01, -1.26595333e-01, -6.26488626e-02,
       -1.59962341e-01,  3.54078442e-01,  1.67052820e-01,  3.77388418e-01,
        2.70658135e-01, -1.19365001e+00,  1.54774472e-01, -4.30314103e-03,
       -3.74634117e-02,  2.87240088e-01, -5.36167324e-01, -2.35020205e-01,
        1.20018266e-01, -1.21314330e-02,  1.33739695e-01, -9.92217511e-02,
       -3.38183284e-01,  4.63119894e-03,  1.27721593e-01,  3.32795382e-01,
       -1.16878279e-01,  1.77502126e-01,  1.91023648e-01, -1.96677563e-03,
       -2.05309868e-01, -3.72174159e-02, -7.65887136e-03,  9.85615924e-02,
       -7.12802494e-03, -2.44020239e-01,  3.06993335e-01, -1.39057739e-02,
        6.08945750e-02, -1.09703243e-01, -1.40849605e-01, -2.29497492e-01,
       -3.12433809e-01, -5.86952688e-03,  1.62922055e-01,  1.63787857e-01,
       -7.13744938e-01, -1.51950717e-01,  5.01734763e-02, -4.74275261e-01,
       -1.19757396e-03,  1.65967003e-01, -4.98522148e-02,  1.27940908e-01,
       -3.88087988e-01, -2.78764033e+00, -2.93632299e-01, -2.13978156e-01,
        3.37605625e-01,  4.18082774e-02,  1.08011879e-01,  9.32566449e-02,
        1.31855667e-01,  2.55934805e-01, -4.24119979e-01,  2.72668689e-01,
       -3.58581506e-02,  1.20623074e-01,  2.20466077e-01, -3.92202973e-01,
        2.53976911e-01,  9.61508155e-02, -2.85840750e-01,  1.28698558e-01,
       -2.24942282e-01, -2.47478858e-01, -5.50118312e-02,  3.60851325e-02,
        2.13333778e-02,  3.23033258e-02,  7.83332661e-02, -1.45530209e-01,
       -3.85953486e-01,  2.72065163e-01,  7.49611929e-02, -4.90090530e-03,
       -2.13091314e-01,  3.56053561e-02, -1.69711605e-01, -1.43215343e-01,
       -3.36857867e+00,  1.84039921e-01, -9.83320624e-02,  1.80643335e-01,
        2.52142489e-01, -6.89291060e-02,  4.27183479e-01, -2.82547951e-01,
       -3.85432631e-01,  2.05299452e-01, -3.08248121e-02, -2.71482021e-02,
       -1.47220299e-01,  2.11246684e-01,  2.65515447e-01, -8.35688040e-02,
        8.21225494e-02, -3.61077428e-01,  3.23032081e-01,  1.64177671e-01,
        1.82008613e-02, -1.64638653e-01,  1.40093848e-01, -1.98473707e-01,
        2.26043940e-01,  2.20795900e-01, -5.47736347e-01, -1.59349099e-01,
       -1.48858443e-01, -1.12260304e-01,  6.25797659e-02, -4.86703724e-01,
        8.31809938e-02,  1.22433773e-03,  1.00180961e-01, -1.43731073e-01,
       -6.83263550e-03, -3.85978967e-02,  3.79258573e-01,  1.78468138e-01,
       -3.51021856e-01,  1.04560483e+00, -4.39241268e-02,  3.13035369e-01,
        5.79004645e-01,  2.19931453e-01,  1.17117884e-02, -1.82669699e-01,
        2.42458403e-01,  7.56992996e-02, -7.61563033e-02,  2.53879637e-01,
        1.12546289e+00,  1.97535917e-01,  4.92675342e-02, -8.38321075e-02,
        1.66679785e-01,  1.94604993e-01, -1.63311481e-01,  1.94488000e-02,
        2.56632090e-01, -2.88866401e-01,  2.01075543e-02,  4.72090021e-02,
        1.45089924e-01, -3.95416617e-01,  1.04746386e-01, -1.73267052e-01,
        1.25129804e-01, -1.56730920e-01, -2.42132738e-01,  2.09594414e-01,
        5.48866987e-02, -1.03506589e+00,  1.45525366e-01,  1.70061402e-02,
        1.11972079e-01, -3.32851410e-02,  1.25381365e-01,  1.12129338e-01,
       -5.32875478e-01, -6.09211661e-02, -2.42062479e-01,  1.93997677e-02,
       -2.70036101e-01, -3.41009140e-01,  1.92737915e-02,  3.69337015e-02,
       -2.56788641e-01, -3.94779965e-02, -1.09281719e-01,  2.92772859e-01,
        4.49894508e-03,  2.36434281e-01, -1.27370700e-01,  1.32160991e-01,
        3.91249031e-01, -7.28661180e-01,  1.33418635e-01, -8.87298509e-02,
       -1.30183801e-01, -2.81367868e-01,  5.06260293e-03,  7.56573752e-02,
       -3.61628830e-01, -2.91981369e-01, -1.17040373e-01,  4.75986511e-01,
        4.33272980e-02,  2.20674798e-01, -2.29159474e-01,  9.02787521e-02,
       -1.36786029e-01,  6.84395665e-03,  1.00711727e+00,  1.16514089e-02,
       -8.79546255e-02,  3.59492570e-01,  1.02120042e-01,  2.45124698e-01,
        2.20120221e-01,  1.25422284e-01, -3.31215173e-01,  1.41469166e-01,
       -3.52179736e-01,  2.59220414e-03,  2.97151785e-02, -2.11989224e-01,
       -1.55398384e-01, -1.24079302e-01, -2.65300155e-01, -2.27138281e-01,
       -3.81300032e-01, -7.82729626e-01, -1.83507707e-02, -2.74365097e-01,
       -3.17456156e-01,  1.56935930e-01,  4.00586605e-01,  9.04281512e-02,
        4.87140715e-01,  1.23185456e-01,  1.40923634e-01,  2.38139927e-01,
       -1.13875277e-01,  3.48127574e-01,  1.15590736e-01,  2.33150899e-01,
        1.37955263e-01,  1.99686274e-01,  6.00329041e-02,  2.25523338e-01,
        1.53861642e-01, -4.92513508e-01,  4.96128470e-01,  1.42293841e-01,
        6.42394423e-02,  1.69942006e-01, -1.15610018e-01,  1.35149807e-01,
        2.57748842e-01,  2.96848863e-01, -1.60115647e+00,  6.16969243e-02,
        7.45327622e-02,  1.07082007e-02, -9.12645459e-02, -1.75277174e-01,
       -4.11463886e-01,  1.62101254e-01, -1.05103619e-01,  3.47859710e-01,
       -1.83207951e-02, -3.05804480e-02, -5.05604036e-02, -2.00071841e-01,
        9.99048427e-02,  4.33747210e-02, -7.02308044e-02,  1.05447233e-01,
       -2.61119790e-02, -8.89049098e-02, -2.01334879e-01,  3.02110076e-01,
        3.45850945e-01, -2.43101656e-01,  1.17869135e-02,  1.77446872e-01,
       -9.75747630e-02,  1.14730723e-01, -6.64330646e-02,  2.97031879e-01,
        3.33796859e-01, -4.87277061e-01, -7.32707918e-01, -8.62503797e-02,
       -1.18988967e-02,  1.28839135e-01,  1.04386859e-01, -6.79935664e-02,
        3.05282682e-01,  6.61516711e-02, -5.54745018e-01,  3.14622521e-01,
        4.89255041e-01,  8.78824070e-02,  5.32032371e-01, -2.95609772e-01,
       -2.32876733e-01,  2.63838679e-01, -1.36119157e-01, -3.29660326e-01,
        9.69461445e-03, -1.03182152e-01, -2.35178813e-01, -1.12340853e-01,
       -1.41883612e-01,  7.57441744e-02,  1.40840009e-01,  4.95235384e-01,
       -1.20517991e-01, -1.89954340e-01,  1.22440673e-01, -2.25522846e-01,
       -1.66930452e-01,  2.40617264e-02, -3.42096478e-01, -7.38174617e-01,
       -1.43409282e-01, -7.32168928e-02,  6.04855753e-02, -3.62670310e-02,
        2.28883147e-01,  2.19556335e-02, -2.79575109e-01,  1.61575153e-01,
       -7.59481937e-02,  1.72941864e-01,  5.73571809e-02,  8.24779049e-02,
        2.09749222e-01, -2.38079518e-01,  5.22107184e-02, -5.79096340e-02,
        1.83484554e-01,  6.56283438e-01, -1.25086367e-01, -6.86027184e-02,
       -3.54325324e-01, -3.59210700e-01,  1.52078852e-01, -1.33953840e-01,
       -3.60615045e-01, -2.92095393e-01, -4.74322848e-02,  3.63080911e-02,
        1.57870799e-02, -7.51721412e-02, -1.58704240e-02, -1.11969091e-01,
       -1.50783822e-01, -1.98285967e-01, -8.88080671e-02,  1.27742052e-01,
        1.18670724e-01,  1.17972821e-01,  1.05812058e-01,  2.31855929e-01,
        3.21194410e-01,  3.26238900e-01, -3.12048018e-01, -5.18182404e-02,
        7.78028220e-02, -2.13420823e-01, -2.01568846e-02,  1.13783084e-01,
        5.35790734e-02, -4.63774174e-01, -2.13561311e-01, -3.20600420e-01,
        2.03474188e+00,  6.76732004e-01,  9.79137793e-02, -1.52819976e-02,
        2.02821672e-01, -1.20333940e-01,  1.23213120e-01,  2.16515929e-01,
       -2.12428674e-01,  5.21719754e-01, -1.15806624e-01,  9.46541280e-02,
        4.77241678e-03,  4.24311459e-02,  6.63325131e-01,  2.51921237e-01,
        4.56104368e-01, -3.03534806e-01, -4.91257071e-01, -7.14896917e-02,
       -5.21047652e-01,  1.99849948e-01,  2.84271896e-01, -3.62730563e-01,
        1.34612009e-01, -7.76548162e-02,  1.59424156e-01,  1.53246177e-02,
        2.27555763e-02,  3.63220036e-01, -1.15794711e-01,  2.79245555e-01,
        1.49785146e-01,  2.63253957e-01, -8.13606381e-02,  8.99408609e-02,
       -1.60297398e-02, -4.40553010e-01, -2.01837182e-01,  1.18468173e-01,
        6.24379404e-02, -1.99266747e-01,  4.37569916e-01, -1.41273484e-01,
        4.86885421e-02,  3.44694912e-01,  1.62425146e-01, -2.38876522e-01,
        1.89561352e-01,  4.52665001e-01, -3.98558863e-02,  1.40039295e-01,
       -3.72228831e-01,  6.75581098e-02, -2.14779824e-01, -1.94864631e-01,
       -8.88516679e-02, -1.75165519e-01,  1.65730372e-01,  2.68035382e-01,
       -3.05291176e-01,  1.04914479e-01,  2.44675428e-01,  2.56603789e-02,
        6.13392368e-02, -2.87435041e-03, -5.44034764e-02,  3.70319307e-01,
       -3.41063216e-02, -9.43180770e-02, -2.66668573e-03,  4.35332686e-01,
        3.60675365e-01,  1.08663410e-01,  5.80001771e-01,  1.92305893e-01,
        1.68648556e-01,  1.32165760e-01, -1.89863458e-01, -2.11926723e+00,
        1.83572784e-01,  1.74526442e-02,  3.35198790e-02, -1.88153699e-01,
        3.47821385e-01,  1.04763255e-01, -1.78016827e-01,  2.45903194e-01,
       -3.43300216e-02,  5.82642592e-02,  7.01137066e-01,  5.54526687e-01,
        5.04127033e-02,  5.02465479e-02, -7.19493851e-02,  1.83516517e-01,
       -6.12476394e-02,  5.39501496e-02, -8.76239240e-02, -8.93160179e-02,
        1.82046950e-01,  3.61894742e-02, -4.33351785e-01, -1.75111979e-01,
        2.09294662e-01, -8.88676122e-02, -6.93406612e-02,  4.65390049e-02,
        1.50464743e-01, -8.97970349e-02,  1.30411416e-01, -3.96828949e-01,
       -6.34839162e-02,  7.53982598e-03, -2.39798799e-01, -3.56666520e-02,
        2.63355225e-01,  2.30460346e-01, -2.54705232e-02, -1.75369367e-01,
        4.28692430e-01, -4.07950487e-03, -1.77405972e-03, -1.09021552e-02,
       -8.14135894e-02,  4.77911383e-01, -1.85338855e-01,  1.36432797e-01,
       -3.68285596e-01, -1.28035173e-01,  1.55324921e-01,  3.61440070e-02,
        8.35712552e-02,  3.50306630e-01,  1.99597880e-01, -1.70094594e-02,
       -1.17120072e-01,  1.85014606e-02, -4.09483910e-01, -2.79139996e-01,
       -6.33886158e-02, -5.36597474e-03,  3.59344520e-02, -1.72175467e-01,
       -3.97869945e-01, -7.47484639e-02, -1.02191605e-01, -2.26873249e-01,
        1.23031102e-01, -1.73647642e-01,  2.46831356e-03,  8.01948458e-02,
        2.01146320e-01, -5.13028214e-03,  9.95679349e-02,  3.28927875e-01,
        3.31025720e-01,  1.57665499e-02,  5.87379783e-02,  3.76298837e-02,
        1.33374063e-02, -2.33448297e-01, -1.08140193e-01,  2.85801053e-01,
       -6.03986454e+00, -2.39461824e-01, -2.07813978e-01,  2.03061208e-01,
       -1.30141124e-01, -4.14236963e-01, -2.11883560e-01, -2.49635026e-01,
       -3.76682356e-02, -2.27980837e-01, -7.24693611e-02,  7.85023794e-02,
       -1.17354952e-02, -7.14893714e-02,  7.18523979e-01,  2.62254536e-01],
      dtype=float32)

The labels indicating which sentence is positive and negative now go into the `labels` variable

In [ ]:
labels = batch_1[1]

## Model #2: Train/Test Split
Let's now split our datset into a training set and testing set (even though we're using 2,000 sentences from the SST2 training set).

In [ ]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels)

<img src="https://jalammar.github.io/images/distilBERT/bert-distilbert-train-test-split-sentence-embedding.png" />

### [Bonus] Grid Search for Parameters
We can dive into Logistic regression directly with the Scikit Learn default parameters, but sometimes it's worth searching for the best value of the C parameter, which determines regularization strength.

In [ ]:
# parameters = {'C': np.linspace(0.0001, 100, 20)}
# grid_search = GridSearchCV(LogisticRegression(), parameters)
# grid_search.fit(train_features, train_labels)

# print('best parameters: ', grid_search.best_params_)
# print('best scrores: ', grid_search.best_score_)

We now train the LogisticRegression model. If you've chosen to do the gridsearch, you can plug the value of C into the model declaration (e.g. `LogisticRegression(C=5.2)`).

In [ ]:
lr_clf = LogisticRegression()
lr_clf.fit(train_features, train_labels)

LogisticRegression()

<img src="https://jalammar.github.io/images/distilBERT/bert-training-logistic-regression.png" />

## Evaluating Model #2
So how well does our model do in classifying sentences? One way is to check the accuracy against the testing dataset:

In [ ]:
lr_clf.score(test_features, test_labels)

0.824

How good is this score? What can we compare it against? Let's first look at a dummy classifier:

In [ ]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier()

scores = cross_val_score(clf, train_features, train_labels)
print("Dummy classifier score: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Dummy classifier score: 0.515 (+/- 0.00)

So our model clearly does better than a dummy classifier. But how does it compare against the best models?

## Proper SST2 scores
For reference, the [highest accuracy score](http://nlpprogress.com/english/sentiment_analysis.html) for this dataset is currently **96.8**. DistilBERT can be trained to improve its score on this task – a process called **fine-tuning** which updates BERT’s weights to make it achieve a better performance in this sentence classification task (which we can call the downstream task). The fine-tuned DistilBERT turns out to achieve an accuracy score of **90.7**. The full size BERT model achieves **94.9**.



And that’s it! That’s a good first contact with BERT. The next step would be to head over to the documentation and try your hand at [fine-tuning](https://huggingface.co/transformers/examples.html#glue). You can also go back and switch from distilBERT to BERT and see how that works.

### Let's try with fine tunning
We will first tokenize the data and then use Trainer for fine tunning of Bert

In [ ]:

!pip uninstall -y transformers accelerate
!pip install transformers accelerate datasets

Found existing installation: transformers 4.29.2
Uninstalling transformers-4.29.2:
  Successfully uninstalled transformers-4.29.2
Found existing installation: accelerate 0.19.0
Uninstalling accelerate-0.19.0:
  Successfully uninstalled accelerate-0.19.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Using cached transformers-4.29.2-py3-none-any.whl (7.1 MB)
Collecting accelerate
  Using cached accelerate-0.19.0-py3-none-any.whl (219 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (2.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.14.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.27.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.65.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.0.0+cu118)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (9.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.2.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.4.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.8.4)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.18.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->accelerate) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->accelerate) (16.0.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->accelerate) (1.3.0)
Installing collected packages: transformers, accelerate
Successfully installed accelerate-0.19.0 transformers-4.29.2

In [ ]:
import pandas as pd
df = pd.read_csv('https://github.com/clairett/pytorch-sentiment-classification/raw/master/data/SST2/train.tsv', delimiter='\t', header=None)

In [ ]:
#tokenizer.decode(input_ids[0])

In [ ]:
#let's work with datasets
from datasets import load_dataset
from datasets import Dataset

df=df.rename(columns={0: 'text', 1: 'label'})

In [ ]:
df

                                                   text  label
0     a stirring , funny and finally transporting re...      1
1     apparently reassembled from the cutting room f...      0
2     they presume their audience wo n't sit still f...      0
3     this is a visually stunning rumination on love...      1
4     jonathan parker 's bartleby should have been t...      1
...                                                 ...    ...
6915  painful , horrifying and oppressively tragic ,...      1
6916  take care is nicely performed by a quintet of ...      0
6917  the script covers huge , heavy topics in a bla...      0
6918  a seriously bad film with seriously warped log...      0
6919  a deliciously nonsensical comedy about a city ...      1

[6920 rows x 2 columns]

In [ ]:

dataset = Dataset.from_pandas(df)
splitted  = dataset.train_test_split(test_size=0.25)

In [ ]:
splitted

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 5190
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1730
    })
})

In [ ]:
splitted['train'], splitted['test']

(Dataset({
     features: ['text', 'label'],
     num_rows: 5190
 }),
 Dataset({
     features: ['text', 'label'],
     num_rows: 1730
 }))

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", max_length=100, truncation=True)

tokenized_splitted = splitted.map(tokenize_function, batched=True, batch_size=32)
#tokenized_dataset_test = dataset_test.map(tokenize_function, batched=True)

Map:   0%|          | 0/5190 [00:00<?, ? examples/s]

Map:   0%|          | 0/1730 [00:00<?, ? examples/s]

In [ ]:
tokenized_splitted

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 5190
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 1730
    })
})

In [ ]:
tokenized_splitted['train'][23]['input_ids'], tokenized_splitted['train'][1]['label']

([101,
  1996,
  3185,
  2003,
  2471,
  3294,
  11158,
  1999,
  23873,
  1010,
  4474,
  1998,
  8335,
  6832,
  10652,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1)

In [ ]:
len(tokenized_splitted['train'][1]['attention_mask']), len(tokenized_splitted['train'][1]['attention_mask'])

(100, 100)

In [ ]:
from transformers import AutoModelForSequenceClassification

model1 = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_projector.bias', 'vocab_transform.weight', 'vocab_transform.bias', 'vocab_projector.weight', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'pre_classifier.weight', 'classifier.weight', 'pre_classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
model1
#sum(p.numel() for p in model1.parameters() if p.requires_grad)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
import torch
#device = torch.device("cpu") if torch.cuda.is_available() else torch.device("cuda")
#model1.to(device)
#device

In [ ]:
#default arguments
from transformers import TrainingArguments, Trainer

#training_args = TrainingArguments("test_trainer")

In [ ]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
import numpy as np
torch.device("cpu")
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }


training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    warmup_steps=200,
    weight_decay=0.01,
    evaluation_strategy="steps",
    logging_strategy="steps",
    eval_steps=50,
    logging_dir='./logs',
    logging_steps = 50

)

trainer = Trainer(
    model=model1,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=tokenized_splitted['train'],
    eval_dataset=tokenized_splitted['test'],
    #place_model_on_device=True
)

In [ ]:
#from transformers import Trainer

#trainer = Trainer(
#    model=model, args=training_args, train_dataset=tokenized_splitted['train'],
#    eval_dataset=tokenized_splitted['test']
#)

In [ ]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:407: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

TrainOutput(global_step=489, training_loss=0.27013303068274125, metrics={'train_runtime': 171.8627, 'train_samples_per_second': 90.596, 'train_steps_per_second': 2.845, 'total_flos': 402835429116000.0, 'train_loss': 0.27013303068274125, 'epoch': 3.0})

In [ ]:
trainer.evaluate()

{'eval_loss': 0.38103818893432617,
 'eval_accuracy': 0.8867052023121387,
 'eval_f1': 0.8919514884233738,
 'eval_precision': 0.88998899889989,
 'eval_recall': 0.8939226519337017,
 'eval_runtime': 5.145,
 'eval_samples_per_second': 336.249,
 'eval_steps_per_second': 10.69,
 'epoch': 3.0}

In [ ]:
#%load_ext tensorboard
#%tensorboard --logdir logs

In [ ]:
sentence="I am so tired and I still do not know if it works."
sentence="I am not sad."
#sentence="We were happy after the work was done."
#sentence = "It's winter and it  is  snowing outside"
#sentence = "It's winter and it is snowing outside"
tokenized = tokenizer(sentence, padding="max_length", max_length=100, truncation=True)

In [ ]:
preds=trainer.predict([tokenized])
preds

PredictionOutput(predictions=array([[-2.078637 ,  1.7175981]], dtype=float32), label_ids=None, metrics={'test_runtime': 0.0361, 'test_samples_per_second': 27.703, 'test_steps_per_second': 27.703})

In [ ]:
import tensorflow as tf
tf_predictions = tf.nn.softmax(preds.predictions, axis=-1)
tf_predictions.numpy()

array([[0.02196199, 0.97803795]], dtype=float32)

In [ ]:
#torch.cuda.empty_cache()

In [ ]:
from transformers import BartTokenizer, BartForCausalLM

import torch
#sentence = "It's winter and it is snowing outside"
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from transformers import GPTNeoForCausalLM, GPT2Tokenizer

#tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
#model = GPT2LMHeadModel.from_pretrained('gpt2')


tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPTNeoForCausalLM.from_pretrained('EleutherAI/gpt-neo-1.3B')

inputs = tokenizer.encode("Hello, my dog is cute", return_tensors="pt")
outputs = model.generate(inputs, labels=inputs, do_sample=True, temperature=0.9, max_length=100)
tokenizer.decode(outputs[0])

#last_hidden_states = outputs.last_hidden_state

In [ ]:
from transformers import pipeline
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')
generator("EleutherAI has", do_sample=True, min_length=50)

In [ ]:
# set return_num_sequences > 1
beam_outputs = model.generate(
    input_ids,
    max_length = 20,
    num_beams = 5,
    no_repeat_ngram_size = 2,
    num_return_sequences = 5,
    early_stopping = True
)

In [ ]:
for i, beam_output in enumerate(beam_outputs):
      print("{}: {}".format(i, tokenizer.decode(beam_output, skip_special_tokens=True)))

In [ ]:
from transformers import DistilBertModel, DistilBertForSequenceClassification,  DistilBertForTokenClassification, DistilBertForMaskedLM
#tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')
model1 = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
model2 = DistilBertForTokenClassification.from_pretrained('distilbert-base-uncased')
model3 = DistilBertForMaskedLM.from_pretrained('distilbert-base-uncased')

In [ ]:
model

In [ ]:
model1

In [ ]:
model2

In [ ]:
model3

In [ ]:
from transformers import BartModel, BartForSequenceClassification,  BartForConditionalGeneration
#tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model10 = BartModel.from_pretrained('facebook/bart-large')
model11= BartForSequenceClassification.from_pretrained('facebook/bart-large')
model12 = BartForConditionalGeneration.from_pretrained('facebook/bart-large')

In [ ]:
model10

In [ ]:
model11

In [ ]:
model12